# Generated by Django 5.1.5 on 2025-02-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImaginaryObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название объекта')),
            ],
            options={
                'verbose_name': 'Воображаемый объект',
                'verbose_name_plural': 'Воображаемые объекты',
            },
        ),
    ]
